### PR TITLE
comment

### PR DESCRIPTION
**Pull request by NickWhiteman**

### CODE REVIEW

**Review by hekkaaa — COMMENTED** [review]
PLEASE FIX 
`private async static Task<int> Run()`

**Review by hekkaaa — CHANGES_REQUESTED** [review]
FIX
`var ex = x.VsU.Count;`

**Comment by NickWhiteman** [comment]
done

**Comment by NickWhiteman** [comment]
leave

**Comment by NickWhiteman** [comment]
fix 2

**Review by hekkaaa — APPROVED** [review]
YEP

**Pull request merged**
